name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['windows', 'darwin', 'linux']
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build (${{ matrix.platform }})
        run: go build -o dist/drivehash.${{ matrix.platform }}.x64.bin cmd/drivehash/drivehash.go
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: amd64

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: drivehash.${{ matrix.platform }}.x64.bin
          path: dist/drivehash.${{ matrix.platform }}.x64.bin
