name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...
    
    - name: Build (windows)
      run: go build -o dist/drivehash.win.x64.exe cmd/drivehash/drivehash.go
      env:
        GOOS: windows 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: dist/*
